# Production Feature Schemas

# Multiclass Random Forest — 36 features
MULTICLASS_FEATURES = [
    "Bwd_Packet_Length_Std",
    "Bwd_Packet_Length_Mean",
    "Packet_Length_Variance",
    "Average_Packet_Size",
    "Total_Length_of_Bwd_Packets",
    "Avg_Bwd_Segment_Size",
    "Max_Packet_Length",
    "Packet_Length_Mean",
    "Packet_Length_Std",
    "Bwd_Packet_Length_Max",
    "Destination_Port",
    "Subflow_Fwd_Packets",
    "Total_Fwd_Packets",
    "Total_Length_of_Fwd_Packets",
    "Subflow_Bwd_Bytes",
    "Subflow_Fwd_Bytes",
    "min_seg_size_forward",
    "Bwd_Header_Length",
    "Fwd_Packet_Length_Max",
    "act_data_pkt_fwd",
    "Avg_Fwd_Segment_Size",
    "Flow_IAT_Max",
    "Fwd_Header_Length",
    "Fwd_Header_Length.1",
    "PSH_Flag_Count",
    "Flow_IAT_Std",
    "ACK_Flag_Count",
    "Fwd_IAT_Min",
    "Fwd_Packet_Length_Mean",
    "Fwd_IAT_Std",
    "Idle_Min",
    "Init_Win_bytes_backward",
    "Subflow_Bwd_Packets",
    "Init_Win_bytes_forward",
    "Fwd_IAT_Mean",
    "Flow_Bytes_per_s",
]


# Binary Random Forest — 70 features
BINARY_FEATURES = [
    "Destination_Port",
    "Flow_Duration",
    "Total_Fwd_Packets",
    "Total_Backward_Packets",
    "Total_Length_of_Fwd_Packets",
    "Total_Length_of_Bwd_Packets",
    "Fwd_Packet_Length_Max",
    "Fwd_Packet_Length_Min",
    "Fwd_Packet_Length_Mean",
    "Fwd_Packet_Length_Std",
    "Bwd_Packet_Length_Max",
    "Bwd_Packet_Length_Min",
    "Bwd_Packet_Length_Mean",
    "Bwd_Packet_Length_Std",
    "Flow_Bytes_per_s",
    "Flow_Packets_per_s",
    "Flow_IAT_Mean",
    "Flow_IAT_Std",
    "Flow_IAT_Max",
    "Flow_IAT_Min",
    "Fwd_IAT_Total",
    "Fwd_IAT_Mean",
    "Fwd_IAT_Std",
    "Fwd_IAT_Max",
    "Fwd_IAT_Min",
    "Bwd_IAT_Total",
    "Bwd_IAT_Mean",
    "Bwd_IAT_Std",
    "Bwd_IAT_Max",
    "Bwd_IAT_Min",
    "Fwd_PSH_Flags",
    "Fwd_URG_Flags",
    "Fwd_Header_Length",
    "Bwd_Header_Length",
    "Fwd_Packets_per_s",
    "Bwd_Packets_per_s",
    "Min_Packet_Length",
    "Max_Packet_Length",
    "Packet_Length_Mean",
    "Packet_Length_Std",
    "Packet_Length_Variance",
    "FIN_Flag_Count",
    "SYN_Flag_Count",
    "RST_Flag_Count",
    "PSH_Flag_Count",
    "ACK_Flag_Count",
    "URG_Flag_Count",
    "CWE_Flag_Count",
    "ECE_Flag_Count",
    "Down_per_Up_Ratio",
    "Average_Packet_Size",
    "Avg_Fwd_Segment_Size",
    "Avg_Bwd_Segment_Size",
    "Fwd_Header_Length.1",
    "Subflow_Fwd_Packets",
    "Subflow_Fwd_Bytes",
    "Subflow_Bwd_Packets",
    "Subflow_Bwd_Bytes",
    "Init_Win_bytes_forward",
    "Init_Win_bytes_backward",
    "act_data_pkt_fwd",
    "min_seg_size_forward",
    "Active_Mean",
    "Active_Std",
    "Active_Max",
    "Active_Min",
    "Idle_Mean",
    "Idle_Std",
    "Idle_Max",
    "Idle_Min",
]


# Backward compatibility
FINAL_FEATURES = MULTICLASS_FEATURES